<a href="https://colab.research.google.com/github/dhyan1999/Royal-DL/blob/master/Insuarance_Royal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Set**

Columns

age: age of primary beneficiary

sex: insurance contractor gender, female, male

bmi: Body mass index, providing an understanding of body, weights that are relatively high or low relative to height,
objective index of body weight (kg / m ^ 2) using the ratio of height to weight, ideally 18.5 to 24.9

children: Number of children covered by health insurance / Number of dependents

smoker: Smoking

region: the beneficiary's residential area in the US, northeast, southeast, southwest, northwest.

charges: Individual medical costs billed by health insurance

In [1]:
import numpy as np
import pandas as pd
import keras.utils as to_categorical
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset = pd.read_csv('/content/datasets_13720_18513_insurance.csv')
dataset.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:

encoder = LabelEncoder()
dataset['sex'] = encoder.fit_transform(dataset['sex'])
dataset['smoker'] = encoder.fit_transform(dataset['smoker'])
dataset['region'] = encoder.fit_transform(dataset['region'])

dataset['age'] = (dataset['age']-dataset['age'].mean())/dataset['age'].max()
dataset['sex'] = (dataset['sex']-dataset['sex'].mean())/dataset['sex'].max()
dataset['bmi'] = (dataset['bmi']-dataset['bmi'].mean())/dataset['bmi'].max()
dataset['children'] = (dataset['children']-dataset['children'].mean())/dataset['children'].max()
dataset['smoker'] = (dataset['smoker']-dataset['smoker'].mean())/dataset['smoker'].max()
dataset['region'] = (dataset['region']-dataset['region'].mean())/dataset['region'].max()
dataset['charges'] = (dataset['charges']-dataset['charges'].mean())/dataset['charges'].max()
dataset.head()

age       sex       bmi  children    smoker    region   charges
0 -0.315735 -0.505232 -0.052012 -0.218984  0.795217  0.494768  0.056680
1 -0.331360  0.494768  0.058472 -0.018984 -0.204783  0.161435 -0.181038
2 -0.175110  0.494768  0.043979  0.381016 -0.204783  0.161435 -0.138324
3 -0.096985  0.494768 -0.149791 -0.218984 -0.204783 -0.171898  0.136647
4 -0.112610  0.494768 -0.033567 -0.218984 -0.204783 -0.171898 -0.147460

In [4]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
x = dataset.iloc[:,:6].values
y = dataset.iloc[:,6].values

In [6]:
x

array([[-0.31573477, -0.50523169, -0.05201199, -0.21898356,  0.79521674,
         0.49476831],
       [-0.33135977,  0.49476831,  0.05847173, -0.01898356, -0.20478326,
         0.16143498],
       [-0.17510977,  0.49476831,  0.04397898,  0.38101644, -0.20478326,
         0.16143498],
       ...,
       [-0.33135977, -0.50523169,  0.11644275, -0.21898356, -0.20478326,
         0.16143498],
       [-0.28448477, -0.50523169, -0.09153768, -0.21898356, -0.20478326,
         0.49476831],
       [ 0.34051523, -0.50523169, -0.02999053, -0.21898356,  0.79521674,
        -0.17189836]])

In [7]:
y

array([ 0.0566799 , -0.18103799, -0.13832368, ..., -0.18253898,
       -0.17660972,  0.24887614])

In [8]:
### Split the data into training & testing samples
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20,random_state=1)

In [9]:
xtrain

array([[ 0.21551523, -0.50523169, -0.07648027, -0.21898356, -0.20478326,
        -0.17189836],
       [ 0.21551523,  0.49476831, -0.17435341, -0.01898356, -0.20478326,
         0.49476831],
       [-0.33135977,  0.49476831,  0.12472432, -0.21898356, -0.20478326,
         0.16143498],
       ...,
       [ 0.18426523, -0.50523169,  0.08086962,  0.18101644,  0.79521674,
        -0.50523169],
       [ 0.01239023, -0.50523169, -0.15891957,  0.18101644,  0.79521674,
         0.16143498],
       [ 0.27801523,  0.49476831, -0.05125912, -0.01898356, -0.20478326,
         0.16143498]])

In [10]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam
model = Sequential()

model.add(Dense(12,input_shape=(6,), activation='relu'))
model.add(Dense(6, activation='sigmoid'))
model.add(Dense(1, activation='linear'))

model.compile(Adam(lr=0.1),'mean_squared_error')

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                84        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 78        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 169
Trainable params: 169
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(xtrain,ytrain,epochs = 100)
y_pred = model.predict(xtest)


Epoch 1/100
34/34 [==============================] - 0s 878us/step - loss: 0.0328
Epoch 2/100
34/34 [==============================] - 0s 1ms/step - loss: 0.0085
Epoch 3/100
34/34 [==============================] - 0s 833us/step - loss: 0.0072
Epoch 4/100
34/34 [==============================] - 0s 877us/step - loss: 0.0069
Epoch 5/100
34/34 [==============================] - 0s 813us/step - loss: 0.0070
Epoch 6/100
34/34 [==============================] - 0s 915us/step - loss: 0.0060
Epoch 7/100
34/34 [==============================] - 0s 833us/step - loss: 0.0061
Epoch 8/100
34/34 [==============================] - 0s 894us/step - loss: 0.0069
Epoch 9/100
34/34 [==============================] - 0s 958us/step - loss: 0.0059
Epoch 10/100
34/34 [==============================] - 0s 951us/step - loss: 0.0063
Epoch 11/100
34/34 [==============================] - 0s 848us/step - loss: 0.0056
Epoch 12/100
34/34 [==============================] - 0s 891us/step - loss: 0.0060
Epoch 13/100
34

In [12]:
ytest

array([-0.18227873, -0.03006401, -0.07012387, -0.04530225, -0.17511788,
        0.39949446, -0.06218745, -0.02528299, -0.15994269,  0.09830294,
       -0.01004424, -0.02715994, -0.10870786, -0.09753393, -0.19025986,
       -0.06746218,  0.13664717, -0.10751448,  0.23549278,  0.00301233,
       -0.05563163,  0.43377484, -0.08222864, -0.0756769 , -0.17354361,
       -0.1035862 , -0.07314056, -0.07819834, -0.12380949, -0.15093725,
       -0.02503186, -0.02403267,  0.18194895,  0.32114995,  0.17109045,
       -0.05342524,  0.36956071,  0.07325784, -0.02217346,  0.41484896,
       -0.1398918 , -0.02393724,  0.10159821, -0.01447772, -0.13076242,
        0.26641774,  0.22665469,  0.33560579, -0.05686287,  0.01762535,
       -0.01117786, -0.02178226, -0.17119932, -0.06536924,  0.0612864 ,
       -0.1454631 ,  0.43391371, -0.00981385,  0.14309645, -0.19007284,
       -0.15530322, -0.00199286,  0.07931287, -0.16591246, -0.00829938,
       -0.07064675, -0.04713753,  0.13990834, -0.16561247,  0.02

In [13]:
result = model.evaluate(xtest,ytest)
print(result)
accuracy_ANN = 1 - result
print("Accuracy : {}".format(accuracy_ANN))

9/9 [==============================] - 0s 1ms/step - loss: 0.0053
0.005273804999887943
Accuracy : 0.9947261950001121
