<a href="https://colab.research.google.com/github/dhyan1999/Royal-DL/blob/master/Iris_MLP_Royal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from keras.utils import to_categorical

In [3]:
dataset = pd.read_csv('/Iris.csv')
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
x = dataset.iloc[:,1:5].values
y = dataset.iloc[:,5].values

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values
print(Y)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 

In [5]:
#### Split the data into training and testing
from sklearn.model_selection import train_test_split
xtrain,xtest,y1train,y1test = train_test_split(x,Y,test_size=0.2,random_state=0)

In [ ]:
xtest

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.1, 1.5, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4]])

In [20]:
from keras.models import Sequential  ### For sequential input
from keras.layers import Dense
from keras.optimizers import SGD , Adam ### Optimizers

model = Sequential()

### Now to add layers to our model
### 10 = no of neurons
### 4 neurons is connected to 10 neurons in the next sequential Layer

model.add(Dense(10, input_shape=(4,), activation = 'sigmoid'))

### Adding 1 more layer
model.add(Dense(8, activation='sigmoid'))

### Adding 1 more layer
model.add(Dense(6, activation='sigmoid'))

### Adding Output layer
model.add(Dense(3, activation='softmax'))

### Compile the model
model.compile(Adam(lr = 0.01), 'categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_28 (Dense)             (None, 10)                50        
_________________________________________________________________
dense_29 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_30 (Dense)             (None, 6)                 54        
_________________________________________________________________
dense_31 (Dense)             (None, 3)                 21        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(xtrain,y1train,epochs = 100)
y_pred = model.predict(xtest)

Epoch 1/100
4/4 [==============================] - 0s 4ms/step - loss: 1.1797 - accuracy: 0.3083
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1323 - accuracy: 0.3000
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1080 - accuracy: 0.3667
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1003 - accuracy: 0.3667
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0982 - accuracy: 0.3667
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0985 - accuracy: 0.3667
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0961 - accuracy: 0.3667
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0962 - accuracy: 0.3667
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0950 - accuracy: 0.3667
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0949 - accuracy: 0.3667
Epoch 11/100
4/4 [===========

In [ ]:
###----------------------CONCLUSION---------------------------------------
### I have set random state = 0 and Adam compiler done all the experiments
### With lr = 0.04  Accuracy = 0.9667
### With lr = 1 loss: 1.1038 - accuracy: 0.3583
### With lr = 0.1 loss: 0.0926 - accuracy: 0.9667
### With lr = 0.01 loss: 0.0854 - accuracy: 0.9833
### With lr = 0.001 loss: 0.9860 - accuracy: 0.6917
### So we can say at lr = 0.01 we can get the highest accuracy
### Now by Switching it to SGD Compiler it accuracy Decreases a lot
### loss: 1.0951 - accuracy: 0.3667
### After experimenting in different lr in SGD its accuracy is less than Adam
### So Adam is more efficient than SDG in these case